### ISSUE TITLE
swap parametrs

### ISSUE THREAD

**Issue by tfe2012** [ongr-io/RouterBundle#16]
https://github.com/ongr-io/RouterBundle/blob/6409e2ea60b1ffa6f81ce049ecd655eaf9715564/Routing/SeoUrlMatcher.php#L204

otherwise you got query like :
"should": [
                {
                    "match": {
                        "PlayStation_4\/1001-Spikes\/": {
                            "query": "urls.url"
                        }
                    }
                }
            ]

**Comment by GrandLTU** [comment]
closed in #27.
