### ISSUE TITLE
Make trailing slash in UrlMatcher optional

### ISSUE THREAD

**Issue by tautelis** [ongr-io/RouterBundle#28]
Please make this step optional and controlled by the configuration as it is done in fox-seo bundle:
https://github.com/ongr-io/RouterBundle/blob/912d0df37bf90edf865d9cdbbe48547627efbc5b/Routing/SeoUrlMatcher.php#L109

**Comment by saimaz** [comment]
The solution would be to introduce a posibility to let inject your own rule of matching. Because right now some wants a trailing slash and some not.

**Comment by murnieza** [comment]
Any progress with this issue?

**Comment by saimaz** [comment]
After we will merge this https://github.com/ongr-io/RouterBundle/pull/39 PR it will be solved.

**Comment by murnieza** [comment]
Cool :+1:

**Comment by murnieza** [comment]
I don't see how https://github.com/ongr-io/RouterBundle/pull/39/files#diff-cc94cc2740c52fafa5d2b92068801959R104 resolved this issue.

**Comment by saimaz** [comment]
Chain routers solves by allowing to use any router logic you need. Now you can easily inject your own router and disable ongr or symfony. Eventually we also will introduce events in the ongr router to help modify request and the other variables.

**Comment by murnieza** [comment]
This can be achieved by adding custom router to chain.

**Comment by asev** [comment]
IMHO trailing slashes should be removed in default behaviour. It is more common to have urls without trailing slash, than with it.

At current implementation you will have to write custom router for nice *.html routes (i.e. /fancy-shorts.html, /red-jeans.html).

**Comment by saimaz** [comment]
Already implements. Now if you want trailing slash at the end you have to write your own EventListener or new route matcher. See the docs for more info.
