### ISSUE TITLE
UrlObject should not be deprecated

### ISSUE THREAD

**Issue by murnieza** [ongr-io/RouterBundle#46]
As seen at https://github.com/ongr-io/RouterBundle/blob/2745eb22944afbe0cafe022e5fa81406d480a136/Document/UrlObject.php#L19 `UrlObject` is deprecated in favour of `UrlNested`.
`UrlNested` can't be used for urls because ES "flattens" nested entities and it is impossible to query for exact url/key pair.

**Comment by saimaz** [comment]
`UrlObject` were removed.
