### ISSUE TITLE
Multi-type repository is used

### ISSUE THREAD

**Issue by murnieza** [ongr-io/RouterBundle#54]
Router bundle uses multi-type repository for URL matching [here](https://github.com/ongr-io/RouterBundle/blob/122c9cb8fed821aa0979b714ed36d66f53f2c91c/Routing/SeoUrlMatcher.php#L232).

 ESB is about to [remove](https://github.com/ongr-io/ElasticsearchBundle/issues/487) multi-type support for repositories. Keep this in mind.

**Comment by saimaz** [comment]
Not iw uses managers client to request an index instead of types.
