### ISSUE TITLE
Router lowercases type names

### ISSUE THREAD

**Issue by murnieza** [ongr-io/RouterBundle#55]
[In this line](https://github.com/ongr-io/RouterBundle/blob/d6aa593129b3d876a5fd4c539e889e5e8665602c/Routing/SeoUrlMatcher.php#L73-L73) every type is lowercased, so router does not work with types having capital letters in name because of [this check](https://github.com/ongr-io/RouterBundle/blob/d6aa593129b3d876a5fd4c539e889e5e8665602c/Routing/SeoUrlMatcher.php#L240).

**Comment by saimaz** [comment]
`SeoURLMatcher` were removed.
