### ISSUE TITLE
Not work SeoUrlMatcher

### ISSUE THREAD

**Issue by tadcka** [ongr-io/RouterBundle#61]
https://github.com/ongr-io/RouterBundle/blob/master/Routing/SeoUrlMatcher.php#L230 because
https://github.com/ongr-io/ElasticsearchBundle/blob/master/Service/Manager.php#L157

**Comment by saimaz** [comment]
RouterBundle `master` branch is under development. There is no surprise it's not working. It will be fixed until stable release.

Currently ElasticsearchBundle's Repository was changed to support single elasticsearch type instead of multiple. That's why this error occurs.
