### ISSUE TITLE
Url field name should be configurable

### ISSUE THREAD

**Issue by mvar** [ongr-io/RouterBundle#65]
Url field name should be configurable and should work independently from property visibility (i.e. public property or setter/getter).

**Comment by saimaz** [comment]
No it should not. If the user really need some different url field, he could create his own route provider/generator. Or what we can do is to add few event dispatchers in our route provider and generator.

For now it might look not strongly (don't find appropriate word) that only possible access of this field is within a public value. And so be it.

**Comment by mvar** [comment]
If we leave it non-configurable, we should at least add setter/getter and change visibility of `$url` to private/protected.

**Comment by saimaz** [comment]
Implemented in #73

**Comment by saimaz** [comment]
This is solved in #75, the Route loader uses getter to get field. User can use whatever name he wants, the only requirement is to implement an interface with `getUrl()`.
