### ISSUE TITLE
Use @ParamConverter instead of custom matcher

### ISSUE THREAD

**Issue by tautrimas** [ongr-io/RouterBundle#9]
Remove **SeoUrlMatcher** and convert it to custom [@ParamConverter](http://symfony.com/doc/2.3/bundles/SensioFrameworkExtraBundle/annotations/converters.html).

Remember to set `$seoKey` in addition to resolved document. Example of [setting request attribute](https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/48547ed5ce820a7bbd7aef544c809e216362bc20/Request/ParamConverter/DoctrineParamConverter.php#L69).

**Configuration** should no longer be needed.

**SeoUrlGenerator** should be removed. Instread, **SeoAwareTrait** should contain a method:

```php
/**
 * Returns document's SEO URL optionally by key.
 */
public function getSeoSlug($key = null);
```

**Twig** usage:

```twig
url(project_product, { url: document.getSeoSlug() } )
```

Documents should contain at least **one SEO URL at all times**. One possibility to achieve that is to always add URL like `/product/faadbaad`. Then, no secondary route is needed at all.

**Comment by martiis** [comment]
How about creating a custom route provider for symfony-cmf dynamic router? `@ParamConverter` sit's on top of symfony router, that means default symfony router does his job and then ParamCoverters does his by modifying request attributes which came from router. 

Symfony-cmf has dynamic router that can accept custom providers.

**Comment by tautrimas** [comment]
Yes, we have investigated this and this is adds only another layer and increases complexity. `@ParamConverter` is much cleaner solution.

There is also a possible problem, because router will have `pattern: /{slug}`. That matches everything and since we have `category`, `product`, `content`, etc. there is a risk of having multiple ESB queries being run. Custom forced caching service class might help.

**Comment by martiis** [comment]
But we will be forced to use annotated routing. Symfony-cmf router provides two solutions:
 - `ChainedRouter` which contains a number of routers (even symfony default can be included) and tries to match at least one router. **This is not what we want IMO**.
 -  `DynamicRouter` *is built to be customized. Both route matching and URL generation services can be injected, and the provided route matcher and URL generator classes are built to be further customizable.* It does not extend symfony router (just implements interfaces), it is a cleaner current ongr router. **GOLD**!
